// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/commands.dart';
import 'api/models.dart';
import 'api/monitor.dart';
import 'api/scanner.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'core/config.dart';
import 'core/models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 225659152;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_frontend',
        ioDirectory: '../backend/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<String>> crateApiScannerDetectLocalRanges();

  Future<List<CommandResult>> crateApiCommandsExecuteBatchCommand({
    required List<String> targetIps,
    required MinerCommand command,
    MinerCredentials? credentials,
  });

  AppSettings crateApiSettingsGetAppSettings();

  Future<List<Miner>> crateApiMonitorGetCurrentMiners();

  Future<List<PoolConfig>> crateApiCommandsGetMinerPools({required String ip});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  void crateApiSettingsSaveAppSettings({required AppSettings settings});

  Future<CommandResult> crateApiCommandsSetMinerPools({
    required String ip,
    required List<PoolConfig> pools,
  });

  Future<CommandResult> crateApiCommandsSetMinerPowerMode({
    required String ip,
    required bool sleep,
  });

  Future<void> crateApiMonitorStartMonitoring({required List<Miner> miners});

  Future<List<Miner>> crateApiScannerStartScan({required String ipRange});

  Future<void> crateApiMonitorStopMonitoring();

  Future<String> crateApiCommandsTestConnection({required String ip});

  Future<String> crateApiScannerValidateIpRange({required String range});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<String>> crateApiScannerDetectLocalRanges() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannerDetectLocalRangesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerDetectLocalRangesConstMeta =>
      const TaskConstMeta(debugName: "detect_local_ranges", argNames: []);

  @override
  Future<List<CommandResult>> crateApiCommandsExecuteBatchCommand({
    required List<String> targetIps,
    required MinerCommand command,
    MinerCredentials? credentials,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(targetIps, serializer);
          sse_encode_box_autoadd_miner_command(command, serializer);
          sse_encode_opt_box_autoadd_miner_credentials(credentials, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_command_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommandsExecuteBatchCommandConstMeta,
        argValues: [targetIps, command, credentials],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsExecuteBatchCommandConstMeta =>
      const TaskConstMeta(
        debugName: "execute_batch_command",
        argNames: ["targetIps", "command", "credentials"],
      );

  @override
  AppSettings crateApiSettingsGetAppSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsGetAppSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsGetAppSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_app_settings", argNames: []);

  @override
  Future<List<Miner>> crateApiMonitorGetCurrentMiners() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_miner,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMonitorGetCurrentMinersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMonitorGetCurrentMinersConstMeta =>
      const TaskConstMeta(debugName: "get_current_miners", argNames: []);

  @override
  Future<List<PoolConfig>> crateApiCommandsGetMinerPools({required String ip}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pool_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommandsGetMinerPoolsConstMeta,
        argValues: [ip],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsGetMinerPoolsConstMeta =>
      const TaskConstMeta(debugName: "get_miner_pools", argNames: ["ip"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiSettingsSaveAppSettings({required AppSettings settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_app_settings(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsSaveAppSettingsConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSaveAppSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "save_app_settings",
        argNames: ["settings"],
      );

  @override
  Future<CommandResult> crateApiCommandsSetMinerPools({
    required String ip,
    required List<PoolConfig> pools,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          sse_encode_list_pool_config(pools, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_command_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommandsSetMinerPoolsConstMeta,
        argValues: [ip, pools],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsSetMinerPoolsConstMeta =>
      const TaskConstMeta(
        debugName: "set_miner_pools",
        argNames: ["ip", "pools"],
      );

  @override
  Future<CommandResult> crateApiCommandsSetMinerPowerMode({
    required String ip,
    required bool sleep,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          sse_encode_bool(sleep, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_command_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommandsSetMinerPowerModeConstMeta,
        argValues: [ip, sleep],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsSetMinerPowerModeConstMeta =>
      const TaskConstMeta(
        debugName: "set_miner_power_mode",
        argNames: ["ip", "sleep"],
      );

  @override
  Future<void> crateApiMonitorStartMonitoring({required List<Miner> miners}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_miner(miners, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMonitorStartMonitoringConstMeta,
        argValues: [miners],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMonitorStartMonitoringConstMeta =>
      const TaskConstMeta(debugName: "start_monitoring", argNames: ["miners"]);

  @override
  Future<List<Miner>> crateApiScannerStartScan({required String ipRange}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ipRange, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_miner,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiScannerStartScanConstMeta,
        argValues: [ipRange],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerStartScanConstMeta =>
      const TaskConstMeta(debugName: "start_scan", argNames: ["ipRange"]);

  @override
  Future<void> crateApiMonitorStopMonitoring() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMonitorStopMonitoringConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMonitorStopMonitoringConstMeta =>
      const TaskConstMeta(debugName: "stop_monitoring", argNames: []);

  @override
  Future<String> crateApiCommandsTestConnection({required String ip}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCommandsTestConnectionConstMeta,
        argValues: [ip],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsTestConnectionConstMeta =>
      const TaskConstMeta(debugName: "test_connection", argNames: ["ip"]);

  @override
  Future<String> crateApiScannerValidateIpRange({required String range}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(range, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScannerValidateIpRangeConstMeta,
        argValues: [range],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannerValidateIpRangeConstMeta =>
      const TaskConstMeta(debugName: "validate_ip_range", argNames: ["range"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppSettings dco_decode_app_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppSettings(
      antminerCredentials: dco_decode_miner_credentials(arr[0]),
      whatsminerCredentials: dco_decode_miner_credentials(arr[1]),
      scanThreadCount: dco_decode_u_32(arr[2]),
      monitorInterval: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_settings(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  MinerCommand dco_decode_box_autoadd_miner_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_miner_command(raw);
  }

  @protected
  MinerCredentials dco_decode_box_autoadd_miner_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_miner_credentials(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CommandResult dco_decode_command_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CommandResult(
      ip: dco_decode_String(arr[0]),
      success: dco_decode_bool(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CommandResult> dco_decode_list_command_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_command_result).toList();
  }

  @protected
  List<Miner> dco_decode_list_miner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_miner).toList();
  }

  @protected
  List<double?> dco_decode_list_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_opt_box_autoadd_f_64).toList();
  }

  @protected
  List<int?> dco_decode_list_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_opt_box_autoadd_u_32).toList();
  }

  @protected
  List<PoolConfig> dco_decode_list_pool_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pool_config).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Miner dco_decode_miner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Miner(
      ip: dco_decode_String(arr[0]),
      model: dco_decode_opt_String(arr[1]),
      status: dco_decode_miner_status(arr[2]),
      stats: dco_decode_miner_stats(arr[3]),
      lastUpdated: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  MinerCommand dco_decode_miner_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MinerCommand_Reboot();
      case 1:
        return MinerCommand_BlinkLed();
      case 2:
        return MinerCommand_StopBlink();
      case 3:
        return MinerCommand_SetPools(
          pools: dco_decode_list_pool_config(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  MinerCredentials dco_decode_miner_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MinerCredentials(
      username: dco_decode_String(arr[0]),
      password: dco_decode_String(arr[1]),
    );
  }

  @protected
  MinerStats dco_decode_miner_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 19)
      throw Exception('unexpected arr length: expect 19 but see ${arr.length}');
    return MinerStats(
      hashrateRt: dco_decode_f_64(arr[0]),
      hashrateAvg: dco_decode_f_64(arr[1]),
      tempOutletMin: dco_decode_list_opt_box_autoadd_f_64(arr[2]),
      tempOutletMax: dco_decode_list_opt_box_autoadd_f_64(arr[3]),
      tempInletMin: dco_decode_list_opt_box_autoadd_f_64(arr[4]),
      tempInletMax: dco_decode_list_opt_box_autoadd_f_64(arr[5]),
      fanSpeeds: dco_decode_list_opt_box_autoadd_u_32(arr[6]),
      uptime: dco_decode_u_64(arr[7]),
      pool1: dco_decode_opt_String(arr[8]),
      worker1: dco_decode_opt_String(arr[9]),
      pool2: dco_decode_opt_String(arr[10]),
      worker2: dco_decode_opt_String(arr[11]),
      pool3: dco_decode_opt_String(arr[12]),
      worker3: dco_decode_opt_String(arr[13]),
      model: dco_decode_opt_String(arr[14]),
      firmware: dco_decode_opt_String(arr[15]),
      software: dco_decode_opt_String(arr[16]),
      hardware: dco_decode_opt_String(arr[17]),
      macAddress: dco_decode_opt_String(arr[18]),
    );
  }

  @protected
  MinerStatus dco_decode_miner_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MinerStatus.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  MinerCredentials? dco_decode_opt_box_autoadd_miner_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_miner_credentials(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PoolConfig dco_decode_pool_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PoolConfig(
      url: dco_decode_String(arr[0]),
      worker: dco_decode_String(arr[1]),
      password: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_antminerCredentials = sse_decode_miner_credentials(deserializer);
    var var_whatsminerCredentials = sse_decode_miner_credentials(deserializer);
    var var_scanThreadCount = sse_decode_u_32(deserializer);
    var var_monitorInterval = sse_decode_u_64(deserializer);
    return AppSettings(
      antminerCredentials: var_antminerCredentials,
      whatsminerCredentials: var_whatsminerCredentials,
      scanThreadCount: var_scanThreadCount,
      monitorInterval: var_monitorInterval,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_settings(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  MinerCommand sse_decode_box_autoadd_miner_command(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_miner_command(deserializer));
  }

  @protected
  MinerCredentials sse_decode_box_autoadd_miner_credentials(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_miner_credentials(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CommandResult sse_decode_command_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ip = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return CommandResult(ip: var_ip, success: var_success, error: var_error);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CommandResult> sse_decode_list_command_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CommandResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_command_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<Miner> sse_decode_list_miner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Miner>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_miner(deserializer));
    }
    return ans_;
  }

  @protected
  List<double?> sse_decode_list_opt_box_autoadd_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <double?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_box_autoadd_f_64(deserializer));
    }
    return ans_;
  }

  @protected
  List<int?> sse_decode_list_opt_box_autoadd_u_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <int?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_box_autoadd_u_32(deserializer));
    }
    return ans_;
  }

  @protected
  List<PoolConfig> sse_decode_list_pool_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PoolConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pool_config(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Miner sse_decode_miner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ip = sse_decode_String(deserializer);
    var var_model = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_miner_status(deserializer);
    var var_stats = sse_decode_miner_stats(deserializer);
    var var_lastUpdated = sse_decode_u_64(deserializer);
    return Miner(
      ip: var_ip,
      model: var_model,
      status: var_status,
      stats: var_stats,
      lastUpdated: var_lastUpdated,
    );
  }

  @protected
  MinerCommand sse_decode_miner_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return MinerCommand_Reboot();
      case 1:
        return MinerCommand_BlinkLed();
      case 2:
        return MinerCommand_StopBlink();
      case 3:
        var var_pools = sse_decode_list_pool_config(deserializer);
        return MinerCommand_SetPools(pools: var_pools);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  MinerCredentials sse_decode_miner_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    return MinerCredentials(username: var_username, password: var_password);
  }

  @protected
  MinerStats sse_decode_miner_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hashrateRt = sse_decode_f_64(deserializer);
    var var_hashrateAvg = sse_decode_f_64(deserializer);
    var var_tempOutletMin = sse_decode_list_opt_box_autoadd_f_64(deserializer);
    var var_tempOutletMax = sse_decode_list_opt_box_autoadd_f_64(deserializer);
    var var_tempInletMin = sse_decode_list_opt_box_autoadd_f_64(deserializer);
    var var_tempInletMax = sse_decode_list_opt_box_autoadd_f_64(deserializer);
    var var_fanSpeeds = sse_decode_list_opt_box_autoadd_u_32(deserializer);
    var var_uptime = sse_decode_u_64(deserializer);
    var var_pool1 = sse_decode_opt_String(deserializer);
    var var_worker1 = sse_decode_opt_String(deserializer);
    var var_pool2 = sse_decode_opt_String(deserializer);
    var var_worker2 = sse_decode_opt_String(deserializer);
    var var_pool3 = sse_decode_opt_String(deserializer);
    var var_worker3 = sse_decode_opt_String(deserializer);
    var var_model = sse_decode_opt_String(deserializer);
    var var_firmware = sse_decode_opt_String(deserializer);
    var var_software = sse_decode_opt_String(deserializer);
    var var_hardware = sse_decode_opt_String(deserializer);
    var var_macAddress = sse_decode_opt_String(deserializer);
    return MinerStats(
      hashrateRt: var_hashrateRt,
      hashrateAvg: var_hashrateAvg,
      tempOutletMin: var_tempOutletMin,
      tempOutletMax: var_tempOutletMax,
      tempInletMin: var_tempInletMin,
      tempInletMax: var_tempInletMax,
      fanSpeeds: var_fanSpeeds,
      uptime: var_uptime,
      pool1: var_pool1,
      worker1: var_worker1,
      pool2: var_pool2,
      worker2: var_worker2,
      pool3: var_pool3,
      worker3: var_worker3,
      model: var_model,
      firmware: var_firmware,
      software: var_software,
      hardware: var_hardware,
      macAddress: var_macAddress,
    );
  }

  @protected
  MinerStatus sse_decode_miner_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MinerStatus.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MinerCredentials? sse_decode_opt_box_autoadd_miner_credentials(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_miner_credentials(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PoolConfig sse_decode_pool_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_worker = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    return PoolConfig(url: var_url, worker: var_worker, password: var_password);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_miner_credentials(self.antminerCredentials, serializer);
    sse_encode_miner_credentials(self.whatsminerCredentials, serializer);
    sse_encode_u_32(self.scanThreadCount, serializer);
    sse_encode_u_64(self.monitorInterval, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_miner_command(
    MinerCommand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_miner_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_miner_credentials(
    MinerCredentials self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_miner_credentials(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_command_result(CommandResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ip, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_command_result(
    List<CommandResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_command_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_miner(List<Miner> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_miner(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_box_autoadd_f_64(
    List<double?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_box_autoadd_f_64(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_box_autoadd_u_32(
    List<int?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_box_autoadd_u_32(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pool_config(
    List<PoolConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pool_config(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_miner(Miner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ip, serializer);
    sse_encode_opt_String(self.model, serializer);
    sse_encode_miner_status(self.status, serializer);
    sse_encode_miner_stats(self.stats, serializer);
    sse_encode_u_64(self.lastUpdated, serializer);
  }

  @protected
  void sse_encode_miner_command(MinerCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MinerCommand_Reboot():
        sse_encode_i_32(0, serializer);
      case MinerCommand_BlinkLed():
        sse_encode_i_32(1, serializer);
      case MinerCommand_StopBlink():
        sse_encode_i_32(2, serializer);
      case MinerCommand_SetPools(pools: final pools):
        sse_encode_i_32(3, serializer);
        sse_encode_list_pool_config(pools, serializer);
    }
  }

  @protected
  void sse_encode_miner_credentials(
    MinerCredentials self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
  }

  @protected
  void sse_encode_miner_stats(MinerStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.hashrateRt, serializer);
    sse_encode_f_64(self.hashrateAvg, serializer);
    sse_encode_list_opt_box_autoadd_f_64(self.tempOutletMin, serializer);
    sse_encode_list_opt_box_autoadd_f_64(self.tempOutletMax, serializer);
    sse_encode_list_opt_box_autoadd_f_64(self.tempInletMin, serializer);
    sse_encode_list_opt_box_autoadd_f_64(self.tempInletMax, serializer);
    sse_encode_list_opt_box_autoadd_u_32(self.fanSpeeds, serializer);
    sse_encode_u_64(self.uptime, serializer);
    sse_encode_opt_String(self.pool1, serializer);
    sse_encode_opt_String(self.worker1, serializer);
    sse_encode_opt_String(self.pool2, serializer);
    sse_encode_opt_String(self.worker2, serializer);
    sse_encode_opt_String(self.pool3, serializer);
    sse_encode_opt_String(self.worker3, serializer);
    sse_encode_opt_String(self.model, serializer);
    sse_encode_opt_String(self.firmware, serializer);
    sse_encode_opt_String(self.software, serializer);
    sse_encode_opt_String(self.hardware, serializer);
    sse_encode_opt_String(self.macAddress, serializer);
  }

  @protected
  void sse_encode_miner_status(MinerStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_miner_credentials(
    MinerCredentials? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_miner_credentials(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_pool_config(PoolConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.worker, serializer);
    sse_encode_String(self.password, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
