// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/commands.dart';
import 'api/models.dart';
import 'api/monitor.dart';
import 'api/scanner.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'core/config.dart';
import 'core/models.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  MinerCommand dco_decode_box_autoadd_miner_command(dynamic raw);

  @protected
  MinerCredentials dco_decode_box_autoadd_miner_credentials(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CommandResult dco_decode_command_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CommandResult> dco_decode_list_command_result(dynamic raw);

  @protected
  List<Miner> dco_decode_list_miner(dynamic raw);

  @protected
  List<double?> dco_decode_list_opt_box_autoadd_f_64(dynamic raw);

  @protected
  List<int?> dco_decode_list_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<PoolConfig> dco_decode_list_pool_config(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Miner dco_decode_miner(dynamic raw);

  @protected
  MinerCommand dco_decode_miner_command(dynamic raw);

  @protected
  MinerCredentials dco_decode_miner_credentials(dynamic raw);

  @protected
  MinerStats dco_decode_miner_stats(dynamic raw);

  @protected
  MinerStatus dco_decode_miner_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  MinerCredentials? dco_decode_opt_box_autoadd_miner_credentials(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PoolConfig dco_decode_pool_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  MinerCommand sse_decode_box_autoadd_miner_command(
    SseDeserializer deserializer,
  );

  @protected
  MinerCredentials sse_decode_box_autoadd_miner_credentials(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CommandResult sse_decode_command_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CommandResult> sse_decode_list_command_result(
    SseDeserializer deserializer,
  );

  @protected
  List<Miner> sse_decode_list_miner(SseDeserializer deserializer);

  @protected
  List<double?> sse_decode_list_opt_box_autoadd_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<int?> sse_decode_list_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<PoolConfig> sse_decode_list_pool_config(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Miner sse_decode_miner(SseDeserializer deserializer);

  @protected
  MinerCommand sse_decode_miner_command(SseDeserializer deserializer);

  @protected
  MinerCredentials sse_decode_miner_credentials(SseDeserializer deserializer);

  @protected
  MinerStats sse_decode_miner_stats(SseDeserializer deserializer);

  @protected
  MinerStatus sse_decode_miner_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  MinerCredentials? sse_decode_opt_box_autoadd_miner_credentials(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PoolConfig sse_decode_pool_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_miner_command(
    MinerCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_miner_credentials(
    MinerCredentials self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_command_result(CommandResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_command_result(
    List<CommandResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_miner(List<Miner> self, SseSerializer serializer);

  @protected
  void sse_encode_list_opt_box_autoadd_f_64(
    List<double?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_u_32(
    List<int?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pool_config(
    List<PoolConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_miner(Miner self, SseSerializer serializer);

  @protected
  void sse_encode_miner_command(MinerCommand self, SseSerializer serializer);

  @protected
  void sse_encode_miner_credentials(
    MinerCredentials self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_miner_stats(MinerStats self, SseSerializer serializer);

  @protected
  void sse_encode_miner_status(MinerStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_miner_credentials(
    MinerCredentials? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pool_config(PoolConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
