// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppSettings {
  final MinerCredentials antminerCredentials;
  final MinerCredentials whatsminerCredentials;
  final int scanThreadCount;
  final BigInt monitorInterval;

  const AppSettings({
    required this.antminerCredentials,
    required this.whatsminerCredentials,
    required this.scanThreadCount,
    required this.monitorInterval,
  });

  @override
  int get hashCode =>
      antminerCredentials.hashCode ^
      whatsminerCredentials.hashCode ^
      scanThreadCount.hashCode ^
      monitorInterval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          antminerCredentials == other.antminerCredentials &&
          whatsminerCredentials == other.whatsminerCredentials &&
          scanThreadCount == other.scanThreadCount &&
          monitorInterval == other.monitorInterval;
}

/// Configuration for miner authentication and connection settings
class MinerCredentials {
  final String username;
  final String password;

  const MinerCredentials({required this.username, required this.password});

  @override
  int get hashCode => username.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MinerCredentials &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          password == other.password;
}
